### ISSUE TITLE
chroot(8) man page has wrong header

### ISSUE THREAD

**Issue by mamccollum** [Projeto-Pindorama/heirloom-ng#25]
The [man page for chroot(8) on line 9](https://github.com/Projeto-Pindorama/heirloom-ng/blob/39b74127d75afec8ae7a2da1baf17d0c0c78a72a/chroot/chroot.8#L9) says "CHMOD" instead of "CHROOT" when rendered at the top of the page. This is my mistake from a few months ago & I apologize for glossing over it. A somewhat trivial issue to open, I know, but I feel it shouldn't go unnoticed.

**Comment by takusuman** [comment]
> The [man page for chroot(8) on line 9](https://github.com/Projeto-Pindorama/heirloom-ng/blob/39b74127d75afec8ae7a2da1baf17d0c0c78a72a/chroot/chroot.8#L9) says "CHMOD" instead of "CHROOT" when rendered at the top of the page. This is my mistake from a few months ago & I apologize for glossing over it. A somewhat trivial issue to open, I know, but I feel it shouldn't go unnoticed.

I'll rewrite the manual page later, but thanks since now for letting me know.

**Comment by takusuman** [comment]
@mamccollum Here, it took a little bit, but I fixed it. 😅 
https://github.com/Projeto-Pindorama/heirloom-ng/commit/be85b38c5382b4acd36149afd7abf42f44e7d61a

Merci for telling me the problem, I haven't seen it before, although reading the manual page many times and even compiling it to HTML for the Heirloom NG website.

I had my UNIX system broken last weeks, that's why I hadn't fixed it before. I was also working and studying, so I hadn't time to fix it before.
Well, as always: anything you need, just ping me.
