### ISSUE TITLE
{Q] Are single binary releases possibe/planned? à la Busybox

### ISSUE THREAD

**Issue by xplshn** [Projeto-Pindorama/heirloom-ng#42]

**Comment by takusuman** [comment]
Never planned this, I do not think it would even be technically possible with this code base.
I think the maximum that can be achieved is to link the programs dynamically and strip the binaries to have the smallest size possible; otherwise, depending on the system, it would be preferable to use [BeastieBox](https://beastiebox.sourceforge.net) --- long forgotten, I do not know if it is still maintained --- or the more popular ToyBox as BusyBox alternatives.
If you would like to combine the classical UNIX usage with the Beastie/Busy/ToyBox minimalism for an embedded system, maybe reworking [UNIXv7 tools](https://www.nordier.com#v7x86) --- liberated and open source'd per a BSD-style licence --- as a single-binary-capable package could be an interesting project.

**Comment by xplshn** [comment]
U-Root does what Crunch does with this; https://github.com/u-root/gobusybox

It is maintained, and it works well enough, maybe a Makefile target for this functionality based on gobuybox?

**Comment by takusuman** [comment]
> It is maintained, and it works well enough, maybe a Makefile target for this functionality based on gobuybox?

It can be a nice experiment, but I'm busy with some subjects recently to implement and test this per myself, so I think I could not help some time soon.
But I can not lie that it is an interesting idea.

**Comment by xplshn** [comment]
Okay, thanks. Marking this as closed.

**Comment by takusuman** [comment]
No problem.
When I get some of my time free, I will take a look at this.
